### ISSUE TITLE
 Unable to converge

### ISSUE THREAD

**Issue by mtchen2016** [SamuelSchmidgall/ES-OnlineMetaLearning#1]
Hello, I downloaded your code and use env_id pentium-v0 in gym. The statement is commented because there is no "set_task" function due to the error reported when running the program. After running 20000 rounds, it is found that reward does not converge. What's the reason?
Using pybullet_envs you provided, no pybullet_data is displayed。

**Comment by SamuelSchmidgall** [comment]
Hello, mtchen. The Pendulum-v0 task usually struggles to converge with the OpenAI-ES optimization, but was left as the default because it doesn't require Mujoco or Pybullet. A better benchmark might by to try either Ant or Hopper. At this moment in time the code is also a bit messy, but to get you started I'd recommend running something from the Networks/nongated folder, as the others are experimental. Also, the pybullet_envs folder is only there for ease of access between my collaborators and me. If you want to use the official pybullet library install it using pip.
